### ISSUE TITLE
Handle derailed trains

### ISSUE THREAD

**Issue by calliecameron** [Zhincore/dynmap-trains#12]
See https://github.com/jenchanws/create-track-map/issues/55 and https://github.com/Zhincore/dynmap-trains/issues/2#issuecomment-2291191127.

Trains that are derailed at server startup don't have the car.leading attribute. Trying to render these throws an error like:

```
Uncaught TypeError: car.leading is undefined
    update trains.js:459
    #updateLayer trains.js:763
    update trains.js:769
    RenderManager trains.js:717
    jQuery 7
    initialize map.js:186
    fire Events.js:203
    _moveEnd Map.js:1241
    _onZoomTransitionEnd Map.js:1717
    z Util.js:231
    _onZoomTransitionEnd Map.js:1716
    setTimeout handler*_animateZoom Map.js:1701
    _tryAnimatedZoom Map.js:1672
    z Util.js:231
    _tryAnimatedZoom Map.js:1669
    setView Map.js:195
    setZoomAround Map.js:249
    _performZoom Map.ScrollWheelZoom.js:83
    setTimeout handler*_onWheelScroll Map.ScrollWheelZoom.js:57
    s DomEvent.js:108
trains.js:459:13
```

and any trains later in the json don't get rendered. Trains without this attribute should be skipped, as in https://github.com/jenchanws/create-track-map/issues/55#issuecomment-1799190751. (Note this isn't fixed in CTM itself yet, either.)

**Comment by Zhincore** [comment]
Hi, could you test this version for me? I did as suggested and it should skip cars with missing leading or trailing attribute.
<https://github.com/Zhincore/dynmap-trains/releases/download/v1.4/trains.js>

**Comment by calliecameron** [comment]
Different error now:

```
Uncaught TypeError: train.cars[0].leading is undefined
    update trains.js:502
    #updateLayer trains.js:763
    createHandler trains.js:745
    #onMessage trains.js:235
    <anonymous> trains.js:213
    connect trains.js:212
    connect trains.js:786
    promise callback*connect trains.js:786
    onAdd trains.js:842
    fire Events.js:203
    _layerAdd Layer.js:116
    whenReady Map.js:1470
    addLayer Layer.js:172
    trains trains.js:856
    initialize map.js:361
    each jQuery
    initialize map.js:360
    onload dynmaputils.js:277
    loadjs dynmaputils.js:274
    initialize map.js:357
    each jQuery
    initialize map.js:355
    DynMap map.js:38
    jQuery 10
    DynMap map.js:28
    <anonymous> (index):49
    jQuery 13
trains.js:502:27
```

**Comment by Zhincore** [comment]
Thank you, I've updated the file, can you try again with the *new* v1.4?

**Comment by calliecameron** [comment]
That fixed it. And it seems to have fixed the glitchy zooming! (though I'd want to test that one on a few different browsers before saying for sure - will get back to you on that)

Trains now also appear in the sidebar, where they didn't before. However, clicking on one in the sidebar gives the error:

```
Uncaught Cannot select map null map.js:479:15
    selectMapAndPan map.js:479
    RenderManager trains.js:741
    jQuery 8
    RenderManager trains.js:737
    #onMessage trains.js:235
    <anonymous> trains.js:213
    (Async: EventHandlerNonNull)
    connect trains.js:212
    connect trains.js:790
    (Async: promise callback)
    connect trains.js:790
    onAdd trains.js:846
    fire Events.js:203
    _layerAdd Layer.js:116
    whenReady Map.js:1470
    addLayer Layer.js:172
    trains trains.js:860
    initialize map.js:361
    each jQuery
    initialize map.js:360
    onload dynmaputils.js:277
    (Async: EventHandlerNonNull)
    loadjs dynmaputils.js:274
    initialize map.js:357
    each jQuery
    initialize map.js:355
    DynMap map.js:38
    jQuery 10
    DynMap map.js:28
    <anonymous> (index):49
    jQuery 13
```

Should it be focusing on the train like clicking on a player in the sidebar does?

**Comment by calliecameron** [comment]
Also, none of the tracks are rendered on the furthest zoom out level, though the trains still are.

**Comment by Zhincore** [comment]
Clicking on train in the sidebar - is it an issue for derailed trains, or for any?

**Comment by calliecameron** [comment]
Any. Trains derailed when the server starts aren't in the sidebar - they're the ones being skipped. Trains derailed during gameplay are in the sidebar but have the same error as trains on the rails.

**Comment by Zhincore** [comment]
Alright, that might be a separate issue then, can you create a new one? I'd like to close this one if it's fixed, just for the sake of order.

**Comment by calliecameron** [comment]
Done, https://github.com/Zhincore/dynmap-trains/issues/13.
