### ISSUE TITLE
Train section in the sidebar cut off on page load

### ISSUE THREAD

**Issue by calliecameron** [Zhincore/dynmap-trains#15]
My server has lots of dimensions (the planets from Ad Astra), so there's a lot of stuff in the sidebar. On page load, the dimensions section is expanded, and some or all of the trains section is off the bottom of the page (see bottom right, should be under players):

![Screenshot from 2024-08-16 14-18-09](https://github.com/user-attachments/assets/1cc0f786-caf5-495e-9c1f-69b31ae47184)

(In this image it's all off the page, in a bigger window it's partly off the page and the down arrow at the bottom is inaccessible.)

After resizing the window - even if it's changed back to the same size afterwards - the trains section is properly scaled:

![Screenshot from 2024-08-16 14-18-22](https://github.com/user-attachments/assets/57ea35ff-8b46-40d2-a84b-d1a7241d1c5a)

**Comment by calliecameron** [comment]
When the train section is only partially visible on page load, mouse wheel scrolling also doesn't work on it till it's been resized.

**Comment by calliecameron** [comment]
This is worse on mobile, because you can't easily realize the browser to force the sidebar to render correctly (using the browser split-screen on android works).

**Comment by Zhincore** [comment]
I would assume the same happens with players though? I'm using Dynmap's list system, so that's probably issue on that side

**Comment by calliecameron** [comment]
Here's the initial state of an even smaller window with a player:

![Screenshot from 2024-08-16 17-22-53](https://github.com/user-attachments/assets/4403f317-24d8-48d0-a65a-ba906391f607)

I'm not really sure what's happening. I'll file a bug against dynmap.

In the meantime, would it be possible for you to trigger dynmap's resize handler at startup as a workaround?

**Comment by calliecameron** [comment]
https://github.com/webbukkit/dynmap/issues/4155
