### ISSUE TITLE
Issue loading World

### ISSUE THREAD

**Issue by OfficialPixelBrush** [Zhincore/dynmap-trains#3]
Screenshot of Error
![image](https://github.com/Zhincore/dynmap-trains/assets/23031327/d482f009-3c77-431e-9b1a-83fbd4cc4c9a)

Screenshot of World Selection
![image](https://github.com/Zhincore/dynmap-trains/assets/23031327/8de98d7b-e804-4bd2-8178-b5a4c698c444)

Screenshot of DynMap
![image](https://github.com/Zhincore/dynmap-trains/assets/23031327/3a5499d5-d7a7-4728-a4f4-6a9efadf5f2b)

Screenshot on the Rails Site (what should be visible)
![image](https://github.com/Zhincore/dynmap-trains/assets/23031327/c05eea94-1e71-4f16-b320-4690fc310bce)

The Dynmap is rendering, but the tracks are not, likely due to my world name having a space in it.

**Comment by Zhincore** [comment]
Hello! Have you specified your world in the config? See this comment https://github.com/Zhincore/dynmap-trains/issues/1#issuecomment-1706450964 for clues on how to find the right names
