### ISSUE TITLE
Not getting any input in Dynmap

### ISSUE THREAD

**Issue by Sora-Canstavia** [Zhincore/dynmap-trains#4]
Hiya, I've followed the readme file and checked through the other issues on the github, but I just, can't for the life of me get this to work, as far as I can see it looks like it should be set up correctly, but I'm not getting any tracks or trains showing on the Dynmap, nor am I seeing any layer options in the layers menu. 

The only thing that I can see that's different between my set up and others potentially is that I'm using the Live Atlas webUI for my Dynmap, which does require overwriting parts of the dynmap/web directory (namely the images folder and the index.html from what I recall), would this render the script for Dynmap Trains incompatible with this? If so, is there any possible workarounds to get it working that you might know of?

**Comment by Zhincore** [comment]
Hi! Yes, I expect this to be incompatible, my script works closely with the Dynmap's original WebUI and Live Atlas seems to be totally independent of the original. 
Only workaround I see is modifying the script to work with Live Atlas, but I am not planning to attempt that any time soon, sorry.

**Comment by Sora-Canstavia** [comment]
Ah, righto, thankyou! I had a feeling when I was typing that out that it might be the case, I might have a look to see if I can mess around with the script or Live Atlas and see if I can't get it to work ^^ 

There's no need to apologise at all, I completely understand not planning on implementing compatibility for this!
